### ISSUE TITLE
Dropdown boxes in Settings of the Tasks app do not work

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/apps#14]
### Affected apps

Tasks
### Expected behaviour

Dropdowns under "Settings" in the Tasks app do not work
### Actual behaviour

The dropdown boxes should work and have content
### Steps to reproduce
1. On Google Chrome, load the Tasks app within Nextcloud
2. Go to Settings at the bottom left
3. Try to click on a dropdown box
### Server configuration

Operating system:
jessie lite

Web server: 
nginx 1.10.1

Database:
mariadb

PHP version:
7.0

nextcloud version:
10
### Client configuration

Browser: Chrome

Operating system:
Windows 7

**Comment by jancborchardt** [comment]
Sorry for not seeing this report. :) This issue belongs in the Tasks app at https://github.com/nextcloud/tasks/issues → please reopen it there if it still occurs.
