### ISSUE TITLE
External pages have a supressed download dialog somehow?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/apps#16]
### Affected apps
External pages

### Expected behaviour
Open an external page inside Nextcloud, and safe a file to disk inside it.

### Actual behaviour
When clicking on the download button in the external app, no download dialog opens (on Firefox).
The external page used for this is a local installation of Draw.io which saves files just fine when opened separately of Nextcloud or if embedded in a dashboard app.

### Steps to reproduce
1. Install external pages plugin
2. Open a local installation of draw.io in it
3. Try saving a file with "save as" for saving it on disk.

### Server configuration
Operating system:
Ubuntu 16.04
Web server: 
Apache2
Database:
MariaDB
PHP version:
7.0
ownCloud version:
Nextcloud 10
### Client configuration
Browser:
Firefox 49.02
Operating system:
Windows8.1
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by jancborchardt** [comment]
If this issue still persists, please reopen it in the new repository at https://github.com/nextcloud/external/issues – likely there’s already an issue for it.
