### ISSUE TITLE
External sites feature request: improved site icon options

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/apps#18]
External sites feature request:

when adding a new site, have nextcloud download the external sites favicon to use as icon (highly useful for orgs using a lot of different web apps internally), with admin option to change to some other icon. E.g. favicon is default, radio button to select to "use other"

Related (feel free to say "start another feature request"): have the dropdown list of icons have "upload new" as an option in list

**Comment by putt1ck** [comment]
Also possibly related or just general bug... make system less dependent on a menu icon file still being in existence (was manually adding in icons for a demo, changed mind about one, deleted old one from file system while adding new, tried to switch to admin in UI and got server fail - feels as if should be more robust about a missing icon for a menu? Touching the file name restored functionality, so it actually being an image isn't important.

As always, feel free to tell me to go post this as a bug somewhere...

**Comment by jancborchardt** [comment]
If this issue still persists, please reopen it in the new repository at https://github.com/nextcloud/external/issues – likely there’s already an issue for it.
