### ISSUE TITLE
External sites feature request: restrict external sites by group in admin options

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/apps#19]
In the admin section, when adding an external site, default to all groups but have option of deselecting groups as needed.

Probably a few use cases, but this one particularly strong; in a school with pupils from 5-14, is possible to have so many sites needed to cover the different age groups that (a) it's going to be messy and hard to find stuff (b) younger pupils may struggle to use the menu to discover *relevant* new stuff

**Comment by j-ed** [comment]
👍 - I think this is a really good request, because it is very often desired to restricted access to individual external sites and not for the app as a whole.

**Comment by ryangorley** [comment]
Restricting visibility of external sites by groups is exactly what we're looking for as well. We use Nextcloud and user groups to give our creative agency clients protected access to their files. With this capability we would be able to integrate Nextcloud to client-specific dashboards, knowledge bases, etc. without their needing to log into multiple sites.

**Comment by DecaTec** [comment]
What about defining external sites per user (in the personal settings)?
Just like the external storage app: The admin can define external storage, but also allow the users to use external storage on their own (in personal settings).

**Comment by greavette** [comment]
Hello Team,

I thought I read somewhere that this suggestion was being implemented in a future release of external sites.  I'm trying to find where I read this.  If someone can confirm if this ability to restrict each external site by group in the Admin panel settings, this would be very beneficial in my opinion.  

Thank you.

**Comment by putt1ck** [comment]
I can confirm External Sites app v3.0.1 in NC13 has this feature. It looks like v3 has an NC13 dependency so isn't showing as an available update on NC12 (where the app is v2.0.3).
