### ISSUE TITLE
imprint App Problems

### ISSUE THREAD

**Issue by rothlive** [nextcloud/apps#22]
### Affected apps
imprint

### Expected behaviour
The app not works only with a cange in info.xml:

dependencies
	nextcloud min-version="11" max-version="11"
	/dependencies

But then the app works not fine.
The Nextcloud Logo is over the Text.
And the settings are not shown.
But the impess works.
See it at :

<a href="http://www.bilder-upload.eu/show.php?file=ecf6b7-1485573090.jpg" target="_blank"><img src="http://www.bilder-upload.eu/thumb/ecf6b7-1485573090.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

NextCloud version:
11.0.1
### Client configuration
Browser:
Firefox
Operating system:
Windows 7
#### Web server error log
No errors

**Comment by MariusBluem** [comment]
App not longer needed. Is now part of theming.

**Comment by rothlive** [comment]
Thanks for the information. Then i will delete it.
