### ISSUE TITLE
apply user_external patch from owncloud

### ISSUE THREAD

**Issue by ftoledo** [nextcloud/apps#25]
### Affected apps
user_external

### Expected behaviour
support strip domain part from login

### Actual behaviour
the user has full domain as part of uid =(

this was solved via this patch:
https://github.com/owncloud/apps/commit/b9c8252cdfbbb70afc5823d9d3f8e55e85008365

please apply ! =)

**Comment by ludgerb** [comment]
This is a duplicate of #1 
And yes, having a duplicate is an indicator showing there is a requirement for this.
