### ISSUE TITLE
Application Filtering by version Nextcloud

### ISSUE THREAD

**Issue by Laupe** [nextcloud/apps#30]
Application Filtering by version Nextcloud.

Would it be possible? It is useful if I want to install applications for the latest version and the author has not yet prepared the application for this.

**Comment by violoncelloCH** [comment]
on apps.nextcloud.com?
then this request would belong to the appstore repo...

**Comment by jancborchardt** [comment]
Nextcloud 16, the latest release, now allows to "Install untested app" if an app developer has not yet uploaded a release for the new version. :)  :rocket:
