### ISSUE TITLE
[NC 13.03] Provide better way to search for a specific app in the app install menu

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/apps#55]
For example, let's search for the app "Bookmarks"

![find-bookmarks-app](https://user-images.githubusercontent.com/24833757/41184743-a4beec28-6b82-11e8-929d-65c99cb6f6a0.png)

**The app is not found.**

The only way to find the app is to look into each app category and search for it by hand.

**Comment by violoncelloCH** [comment]
this would belong to the server repo, because app management is done there
however your issue should be already fixed
