### ISSUE TITLE
Rebrand to Nextcloud

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/apps#7]
Those Apps here are not branded to Nextcloud (e.g. Descriptions, ...).
I will do this in the coming week :)

cc @MorrisJobke

**Comment by nickvergessen** [comment]
*cough* @MariusBluem *cough*

**Comment by MariusBluem** [comment]
Holy S*** ... Totally forgotten the apps repo 😅 I will do this - **this** week 😉 
Sorry for the delay 😒

**Comment by MariusBluem** [comment]
...should I also clean up a bit by deleting some of the apps which were not updated for some times and those with another implementation (user_saml) 😁 @MorrisJobke

**Comment by MorrisJobke** [comment]
> ...should I also clean up a bit by deleting some of the apps which were not updated for some times and those with another implementation (user_saml) 😁 @MorrisJobke

Yes, but not erverything in one PR. split it up ;)

**Comment by jancborchardt** [comment]
Closing because it’s obsolete, we don’t really need to touch these apps anymore. If someone picks them up, they can do it – but should move them to a dedicated repo. :)
