### ISSUE TITLE
External User Support (user_external) Not Working in NextCloud 15.0.0 (max version is 14)

### ISSUE THREAD

**Issue by gabrielmongefranco** [nextcloud/apps#73]
### Affected apps
Tell us which app(s) you are talking about
External User Support (user_external)

### Steps to reproduce
1. Install NextCloud 15 via Snappy image on Debian 9
2. Create admin account.
3. Login as admin.
4. Go to Settings -> Apps -> Disabled Apps
5. Click Enable on External User Support

### Expected behaviour
Tell us what should happen
Application should be successfully enabled.

### Actual behaviour
Tell us what happens instead
Application is not enabled, and instead this error message is shown:

>  This app cannot be installed because the following dependencies are not fulfilled:
> 
>     Server version 14 or lower is required.

### Server configuration

**Operating system**:
Debian 9
**Web server:**
Apache? Whatever is provided with Snap image
**Database:**
Whatever is provided with Snap image
**PHP version:**
Whatever is provided with Snap image
**Server version:** (see your admin page)
15.0.0
**Calendar version:** (see the apps page)
Irrelevant
**Updated from an older installed version or fresh install:**
Fresh install
**Signing status (ownCloud/Nextcloud 9.0 and above):**
???
```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by gabrielmongefranco** [comment]
Also reported issue at: https://github.com/nextcloud/nextcloud-snap/issues/820
The later (nextcloud-snap) seems like a better place for it, so feel free to close the issue here.

**Comment by hno** [comment]
No this issue is not SNAP related. Also happens in Docker image.
I think the issue is that the updated version was not not included in nextcloud 15.0.0 as the app is shipped integrated in NextCloud distribution.
Temporary fix: Manually edit apps/user_external/appinfo/info.xml and change max_version from 14 to 15 as per change 0a33a1ea349ee902738959ef6f8b167f0c345289

**Comment by tflidd** [comment]
App is currently moved into its own repository and will hopefully soon be published via app store:
https://github.com/nextcloud/user_external/issues/22

**Comment by violoncelloCH** [comment]
yes @tflidd, release is on it's way!

**Comment by gabrielmongefranco** [comment]
Great! Good to know, because editing apps/user_external/appinfo/info.xml in
the Snap image is not an option because the file system is read-only. (That
was the first thing I tried before opening the bug reports).

Gabriel.

**Comment by violoncelloCH** [comment]
It's finally here: https://apps.nextcloud.com/apps/user_external
